import React, { Component } from "react";
import { BrowserRouter as Router, Route } from "react-router-dom";

import NavBar from "../elements/NavBar/NavBar";
import Home from "../pages/Home/Home";
import WorkInProgress from "../pages/WorkInProgress/WorkInProgress";
import News from "../pages/News/News";
import Origins from "../pages/Origins/Origins";
import ContactUs from "../pages/ContactUs/ContactUs";
import AboutLcm from "../pages/AboutLcm/AboutLcm";
import WorkingWithLcm from "../pages/WorkingWithLcm/WorkingWithLcm";
import SingleArticle from "../pages/SingleArticle/SingleArticle";
import Footer from "../elements/Footer/Footer";

import "./App.scss";
// import Test from "../Alex/Test/Test";
// import Test from "../illya/Test";

export default class App extends Component {
  state = {
    newsInfo: [
      { category: 'Events', title: 'Genetic Testing Reveals the True Nature of Coffee Varieties', text: 'As the number of Americans who drink coffee every day has increased by 5% over the past five years, more Americans are also turning to espresso-based beverages and cold brew. These are two of the prevailing trends in the new 2020 National Coffee Data Trends (NCDT) report (formerly known as National Coffee Drinking Trends) from the National Coffee Association, which has compiled data on coffee consumption in the United States since 1950. The 2020 report reflects data gathered in pre-COVID-19 America, and of course the long-term economic and social ramifications the coronavirus and its response will have on consumers and the coffee industry are yet to unfold. “The NCDT is the Atlas of American Coffee,” NCA President and CEO Bill Murray said in announcement of the report’s release today. “This year’s release shows just how much Americans rely on the energy, comfort, and normalcy of their favorite brew. “But these are challenging times, and the coffee business is not as usual. NCA encourages everyone in the coffee industry to continue supporting small businesses, governments, health authorities, workers, and every day Americans as we all work together to manage the profound impacts of the coronavirus outbreak.” Released in conjunction with a webinar yesterday following the NCA’s annual convention, which took place in early March in Austin, Texas, the report draws upon several thousand surveys of a nationally representative group of people by age and race. According to the NCA, Americans are drinking more coffee than ever. Here are some of the highlights of the report, which will be available for purchase at the NCA website.', image: './NewsArticlePictures/Footer.png', id: '1' },
      { category: 'How-to', title: 'Selling Coffee During a Pandemic: Email Frequency, Tone and Content', text: 'As the number of Americans who drink coffee every day has increased by 5% over the past five years, more Americans are also turning to espresso-based beverages and cold brew. These are two of the prevailing trends in the new 2020 National Coffee Data Trends (NCDT) report (formerly known as National Coffee Drinking Trends) from the National Coffee Association, which has compiled data on coffee consumption in the United States since 1950. The 2020 report reflects data gathered in pre-COVID-19 America, and of course the long-term economic and social ramifications the coronavirus and its response will have on consumers and the coffee industry are yet to unfold. “The NCDT is the Atlas of American Coffee,” NCA President and CEO Bill Murray said in announcement of the report’s release today. “This year’s release shows just how much Americans rely on the energy, comfort, and normalcy of their favorite brew. “But these are challenging times, and the coffee business is not as usual. NCA encourages everyone in the coffee industry to continue supporting small businesses, governments, health authorities, workers, and every day Americans as we all work together to manage the profound impacts of the coronavirus outbreak.” Released in conjunction with a webinar yesterday following the NCA’s annual convention, which took place in early March in Austin, Texas, the report draws upon several thousand surveys of a nationally representative group of people by age and race. According to the NCA, Americans are drinking more coffee than ever. Here are some of the highlights of the report, which will be available for purchase at the NCA website.', image: './NewsArticlePictures/MainHeaderBackground.png', id: '2' },
      { category: 'News', title: '2020 Coffee and Beverage Trends: Inside Annual Report', text: 'As the number of Americans who drink coffee every day has increased by 5% over the past five years, more Americans are also turning to espresso-based beverages and cold brew. These are two of the prevailing trends in the new 2020 National Coffee Data Trends (NCDT) report (formerly known as National Coffee Drinking Trends) from the National Coffee Association, which has compiled data on coffee consumption in the United States since 1950. The 2020 report reflects data gathered in pre-COVID-19 America, and of course the long-term economic and social ramifications the coronavirus and its response will have on consumers and the coffee industry are yet to unfold. “The NCDT is the Atlas of American Coffee,” NCA President and CEO Bill Murray said in announcement of the report’s release today. “This year’s release shows just how much Americans rely on the energy, comfort, and normalcy of their favorite brew. “But these are challenging times, and the coffee business is not as usual. NCA encourages everyone in the coffee industry to continue supporting small businesses, governments, health authorities, workers, and every day Americans as we all work together to manage the profound impacts of the coronavirus outbreak.” Released in conjunction with a webinar yesterday following the NCA’s annual convention, which took place in early March in Austin, Texas, the report draws upon several thousand surveys of a nationally representative group of people by age and race. According to the NCA, Americans are drinking more coffee than ever. Here are some of the highlights of the report, which will be available for purchase at the NCA website.', image: './NewsArticlePictures/Footer.png', id: '3' },
      { category: 'Community', title: 'New Roaster Kind & Co. Offers a Little Coffee Cheer', text: 'As the number of Americans who drink coffee every day has increased by 5% over the past five years, more Americans are also turning to espresso-based beverages and cold brew. These are two of the prevailing trends in the new 2020 National Coffee Data Trends (NCDT) report (formerly known as National Coffee Drinking Trends) from the National Coffee Association, which has compiled data on coffee consumption in the United States since 1950. The 2020 report reflects data gathered in pre-COVID-19 America, and of course the long-term economic and social ramifications the coronavirus and its response will have on consumers and the coffee industry are yet to unfold. “The NCDT is the Atlas of American Coffee,” NCA President and CEO Bill Murray said in announcement of the report’s release today. “This year’s release shows just how much Americans rely on the energy, comfort, and normalcy of their favorite brew. “But these are challenging times, and the coffee business is not as usual. NCA encourages everyone in the coffee industry to continue supporting small businesses, governments, health authorities, workers, and every day Americans as we all work together to manage the profound impacts of the coronavirus outbreak.” Released in conjunction with a webinar yesterday following the NCA’s annual convention, which took place in early March in Austin, Texas, the report draws upon several thousand surveys of a nationally representative group of people by age and race. According to the NCA, Americans are drinking more coffee than ever. Here are some of the highlights of the report, which will be available for purchase at the NCA website.', image: './NewsArticlePictures/MainHeaderBackground.png', id: '4' },
      { category: 'From Origin', title: 'Selling Coffee During a Pandemic: Email Frequency, Tone and Content', text: 'As the number of Americans who drink coffee every day has increased by 5% over the past five years, more Americans are also turning to espresso-based beverages and cold brew. These are two of the prevailing trends in the new 2020 National Coffee Data Trends (NCDT) report (formerly known as National Coffee Drinking Trends) from the National Coffee Association, which has compiled data on coffee consumption in the United States since 1950. The 2020 report reflects data gathered in pre-COVID-19 America, and of course the long-term economic and social ramifications the coronavirus and its response will have on consumers and the coffee industry are yet to unfold. “The NCDT is the Atlas of American Coffee,” NCA President and CEO Bill Murray said in announcement of the report’s release today. “This year’s release shows just how much Americans rely on the energy, comfort, and normalcy of their favorite brew. “But these are challenging times, and the coffee business is not as usual. NCA encourages everyone in the coffee industry to continue supporting small businesses, governments, health authorities, workers, and every day Americans as we all work together to manage the profound impacts of the coronavirus outbreak.” Released in conjunction with a webinar yesterday following the NCA’s annual convention, which took place in early March in Austin, Texas, the report draws upon several thousand surveys of a nationally representative group of people by age and race. According to the NCA, Americans are drinking more coffee than ever. Here are some of the highlights of the report, which will be available for purchase at the NCA website.', image: './NewsArticlePictures/Footer.png', id: '5' },
      { category: 'Events', title: 'Genetic Testing Reveals the True Nature of Coffee Varieties', text: 'As the number of Americans who drink coffee every day has increased by 5% over the past five years, more Americans are also turning to espresso-based beverages and cold brew. These are two of the prevailing trends in the new 2020 National Coffee Data Trends (NCDT) report (formerly known as National Coffee Drinking Trends) from the National Coffee Association, which has compiled data on coffee consumption in the United States since 1950. The 2020 report reflects data gathered in pre-COVID-19 America, and of course the long-term economic and social ramifications the coronavirus and its response will have on consumers and the coffee industry are yet to unfold. “The NCDT is the Atlas of American Coffee,” NCA President and CEO Bill Murray said in announcement of the report’s release today. “This year’s release shows just how much Americans rely on the energy, comfort, and normalcy of their favorite brew. “But these are challenging times, and the coffee business is not as usual. NCA encourages everyone in the coffee industry to continue supporting small businesses, governments, health authorities, workers, and every day Americans as we all work together to manage the profound impacts of the coronavirus outbreak.” Released in conjunction with a webinar yesterday following the NCA’s annual convention, which took place in early March in Austin, Texas, the report draws upon several thousand surveys of a nationally representative group of people by age and race. According to the NCA, Americans are drinking more coffee than ever. Here are some of the highlights of the report, which will be available for purchase at the NCA website.', image: './NewsArticlePictures/Footer.png', id: '6' },
      { category: 'How-to', title: 'Selling Coffee During a Pandemic: Email Frequency, Tone and Content', text: 'As the number of Americans who drink coffee every day has increased by 5% over the past five years, more Americans are also turning to espresso-based beverages and cold brew. These are two of the prevailing trends in the new 2020 National Coffee Data Trends (NCDT) report (formerly known as National Coffee Drinking Trends) from the National Coffee Association, which has compiled data on coffee consumption in the United States since 1950. The 2020 report reflects data gathered in pre-COVID-19 America, and of course the long-term economic and social ramifications the coronavirus and its response will have on consumers and the coffee industry are yet to unfold. “The NCDT is the Atlas of American Coffee,” NCA President and CEO Bill Murray said in announcement of the report’s release today. “This year’s release shows just how much Americans rely on the energy, comfort, and normalcy of their favorite brew. “But these are challenging times, and the coffee business is not as usual. NCA encourages everyone in the coffee industry to continue supporting small businesses, governments, health authorities, workers, and every day Americans as we all work together to manage the profound impacts of the coronavirus outbreak.” Released in conjunction with a webinar yesterday following the NCA’s annual convention, which took place in early March in Austin, Texas, the report draws upon several thousand surveys of a nationally representative group of people by age and race. According to the NCA, Americans are drinking more coffee than ever. Here are some of the highlights of the report, which will be available for purchase at the NCA website.', image: './NewsArticlePictures/MainHeaderBackground.png', id: '7' },
      { category: 'News', title: '2020 Coffee and Beverage Trends: Inside Annual Report', text: 'As the number of Americans who drink coffee every day has increased by 5% over the past five years, more Americans are also turning to espresso-based beverages and cold brew. These are two of the prevailing trends in the new 2020 National Coffee Data Trends (NCDT) report (formerly known as National Coffee Drinking Trends) from the National Coffee Association, which has compiled data on coffee consumption in the United States since 1950. The 2020 report reflects data gathered in pre-COVID-19 America, and of course the long-term economic and social ramifications the coronavirus and its response will have on consumers and the coffee industry are yet to unfold. “The NCDT is the Atlas of American Coffee,” NCA President and CEO Bill Murray said in announcement of the report’s release today. “This year’s release shows just how much Americans rely on the energy, comfort, and normalcy of their favorite brew. “But these are challenging times, and the coffee business is not as usual. NCA encourages everyone in the coffee industry to continue supporting small businesses, governments, health authorities, workers, and every day Americans as we all work together to manage the profound impacts of the coronavirus outbreak.” Released in conjunction with a webinar yesterday following the NCA’s annual convention, which took place in early March in Austin, Texas, the report draws upon several thousand surveys of a nationally representative group of people by age and race. According to the NCA, Americans are drinking more coffee than ever. Here are some of the highlights of the report, which will be available for purchase at the NCA website.', image: './NewsArticlePictures/Footer.png', id: '8' },
      { category: 'Community', title: 'New Roaster Kind & Co. Offers a Little Coffee Cheer', text: 'As the number of Americans who drink coffee every day has increased by 5% over the past five years, more Americans are also turning to espresso-based beverages and cold brew. These are two of the prevailing trends in the new 2020 National Coffee Data Trends (NCDT) report (formerly known as National Coffee Drinking Trends) from the National Coffee Association, which has compiled data on coffee consumption in the United States since 1950. The 2020 report reflects data gathered in pre-COVID-19 America, and of course the long-term economic and social ramifications the coronavirus and its response will have on consumers and the coffee industry are yet to unfold. “The NCDT is the Atlas of American Coffee,” NCA President and CEO Bill Murray said in announcement of the report’s release today. “This year’s release shows just how much Americans rely on the energy, comfort, and normalcy of their favorite brew. “But these are challenging times, and the coffee business is not as usual. NCA encourages everyone in the coffee industry to continue supporting small businesses, governments, health authorities, workers, and every day Americans as we all work together to manage the profound impacts of the coronavirus outbreak.” Released in conjunction with a webinar yesterday following the NCA’s annual convention, which took place in early March in Austin, Texas, the report draws upon several thousand surveys of a nationally representative group of people by age and race. According to the NCA, Americans are drinking more coffee than ever. Here are some of the highlights of the report, which will be available for purchase at the NCA website.', image: './NewsArticlePictures/MainHeaderBackground.png', id: '9' },
      { category: 'From Origin', title: 'Selling Coffee During a Pandemic: Email Frequency, Tone and Content', text: 'As the number of Americans who drink coffee every day has increased by 5% over the past five years, more Americans are also turning to espresso-based beverages and cold brew. These are two of the prevailing trends in the new 2020 National Coffee Data Trends (NCDT) report (formerly known as National Coffee Drinking Trends) from the National Coffee Association, which has compiled data on coffee consumption in the United States since 1950. The 2020 report reflects data gathered in pre-COVID-19 America, and of course the long-term economic and social ramifications the coronavirus and its response will have on consumers and the coffee industry are yet to unfold. “The NCDT is the Atlas of American Coffee,” NCA President and CEO Bill Murray said in announcement of the report’s release today. “This year’s release shows just how much Americans rely on the energy, comfort, and normalcy of their favorite brew. “But these are challenging times, and the coffee business is not as usual. NCA encourages everyone in the coffee industry to continue supporting small businesses, governments, health authorities, workers, and every day Americans as we all work together to manage the profound impacts of the coronavirus outbreak.” Released in conjunction with a webinar yesterday following the NCA’s annual convention, which took place in early March in Austin, Texas, the report draws upon several thousand surveys of a nationally representative group of people by age and race. According to the NCA, Americans are drinking more coffee than ever. Here are some of the highlights of the report, which will be available for purchase at the NCA website.', image: './NewsArticlePictures/Footer.png', id: '10' },
      { category: 'Events', title: 'Genetic Testing Reveals the True Nature of Coffee Varieties', text: 'As the number of Americans who drink coffee every day has increased by 5% over the past five years, more Americans are also turning to espresso-based beverages and cold brew. These are two of the prevailing trends in the new 2020 National Coffee Data Trends (NCDT) report (formerly known as National Coffee Drinking Trends) from the National Coffee Association, which has compiled data on coffee consumption in the United States since 1950. The 2020 report reflects data gathered in pre-COVID-19 America, and of course the long-term economic and social ramifications the coronavirus and its response will have on consumers and the coffee industry are yet to unfold. “The NCDT is the Atlas of American Coffee,” NCA President and CEO Bill Murray said in announcement of the report’s release today. “This year’s release shows just how much Americans rely on the energy, comfort, and normalcy of their favorite brew. “But these are challenging times, and the coffee business is not as usual. NCA encourages everyone in the coffee industry to continue supporting small businesses, governments, health authorities, workers, and every day Americans as we all work together to manage the profound impacts of the coronavirus outbreak.” Released in conjunction with a webinar yesterday following the NCA’s annual convention, which took place in early March in Austin, Texas, the report draws upon several thousand surveys of a nationally representative group of people by age and race. According to the NCA, Americans are drinking more coffee than ever. Here are some of the highlights of the report, which will be available for purchase at the NCA website.', image: './NewsArticlePictures/Footer.png', id: '11' },
      { category: 'How-to', title: 'Selling Coffee During a Pandemic: Email Frequency, Tone and Content', text: 'As the number of Americans who drink coffee every day has increased by 5% over the past five years, more Americans are also turning to espresso-based beverages and cold brew. These are two of the prevailing trends in the new 2020 National Coffee Data Trends (NCDT) report (formerly known as National Coffee Drinking Trends) from the National Coffee Association, which has compiled data on coffee consumption in the United States since 1950. The 2020 report reflects data gathered in pre-COVID-19 America, and of course the long-term economic and social ramifications the coronavirus and its response will have on consumers and the coffee industry are yet to unfold. “The NCDT is the Atlas of American Coffee,” NCA President and CEO Bill Murray said in announcement of the report’s release today. “This year’s release shows just how much Americans rely on the energy, comfort, and normalcy of their favorite brew. “But these are challenging times, and the coffee business is not as usual. NCA encourages everyone in the coffee industry to continue supporting small businesses, governments, health authorities, workers, and every day Americans as we all work together to manage the profound impacts of the coronavirus outbreak.” Released in conjunction with a webinar yesterday following the NCA’s annual convention, which took place in early March in Austin, Texas, the report draws upon several thousand surveys of a nationally representative group of people by age and race. According to the NCA, Americans are drinking more coffee than ever. Here are some of the highlights of the report, which will be available for purchase at the NCA website.', image: './NewsArticlePictures/MainHeaderBackground.png', id: '12' },
      { category: 'News', title: '2020 Coffee and Beverage Trends: Inside Annual Report', text: 'As the number of Americans who drink coffee every day has increased by 5% over the past five years, more Americans are also turning to espresso-based beverages and cold brew. These are two of the prevailing trends in the new 2020 National Coffee Data Trends (NCDT) report (formerly known as National Coffee Drinking Trends) from the National Coffee Association, which has compiled data on coffee consumption in the United States since 1950. The 2020 report reflects data gathered in pre-COVID-19 America, and of course the long-term economic and social ramifications the coronavirus and its response will have on consumers and the coffee industry are yet to unfold. “The NCDT is the Atlas of American Coffee,” NCA President and CEO Bill Murray said in announcement of the report’s release today. “This year’s release shows just how much Americans rely on the energy, comfort, and normalcy of their favorite brew. “But these are challenging times, and the coffee business is not as usual. NCA encourages everyone in the coffee industry to continue supporting small businesses, governments, health authorities, workers, and every day Americans as we all work together to manage the profound impacts of the coronavirus outbreak.” Released in conjunction with a webinar yesterday following the NCA’s annual convention, which took place in early March in Austin, Texas, the report draws upon several thousand surveys of a nationally representative group of people by age and race. According to the NCA, Americans are drinking more coffee than ever. Here are some of the highlights of the report, which will be available for purchase at the NCA website.', image: './NewsArticlePictures/Footer.png', id: '13' },
      { category: 'Community', title: 'New Roaster Kind & Co. Offers a Little Coffee Cheer', text: 'As the number of Americans who drink coffee every day has increased by 5% over the past five years, more Americans are also turning to espresso-based beverages and cold brew. These are two of the prevailing trends in the new 2020 National Coffee Data Trends (NCDT) report (formerly known as National Coffee Drinking Trends) from the National Coffee Association, which has compiled data on coffee consumption in the United States since 1950. The 2020 report reflects data gathered in pre-COVID-19 America, and of course the long-term economic and social ramifications the coronavirus and its response will have on consumers and the coffee industry are yet to unfold. “The NCDT is the Atlas of American Coffee,” NCA President and CEO Bill Murray said in announcement of the report’s release today. “This year’s release shows just how much Americans rely on the energy, comfort, and normalcy of their favorite brew. “But these are challenging times, and the coffee business is not as usual. NCA encourages everyone in the coffee industry to continue supporting small businesses, governments, health authorities, workers, and every day Americans as we all work together to manage the profound impacts of the coronavirus outbreak.” Released in conjunction with a webinar yesterday following the NCA’s annual convention, which took place in early March in Austin, Texas, the report draws upon several thousand surveys of a nationally representative group of people by age and race. According to the NCA, Americans are drinking more coffee than ever. Here are some of the highlights of the report, which will be available for purchase at the NCA website.', image: './NewsArticlePictures/MainHeaderBackground.png', id: '14' },
      { category: 'From Origin', title: 'Selling Coffee During a Pandemic: Email Frequency, Tone and Content', text: 'As the number of Americans who drink coffee every day has increased by 5% over the past five years, more Americans are also turning to espresso-based beverages and cold brew. These are two of the prevailing trends in the new 2020 National Coffee Data Trends (NCDT) report (formerly known as National Coffee Drinking Trends) from the National Coffee Association, which has compiled data on coffee consumption in the United States since 1950. The 2020 report reflects data gathered in pre-COVID-19 America, and of course the long-term economic and social ramifications the coronavirus and its response will have on consumers and the coffee industry are yet to unfold. “The NCDT is the Atlas of American Coffee,” NCA President and CEO Bill Murray said in announcement of the report’s release today. “This year’s release shows just how much Americans rely on the energy, comfort, and normalcy of their favorite brew. “But these are challenging times, and the coffee business is not as usual. NCA encourages everyone in the coffee industry to continue supporting small businesses, governments, health authorities, workers, and every day Americans as we all work together to manage the profound impacts of the coronavirus outbreak.” Released in conjunction with a webinar yesterday following the NCA’s annual convention, which took place in early March in Austin, Texas, the report draws upon several thousand surveys of a nationally representative group of people by age and race. According to the NCA, Americans are drinking more coffee than ever. Here are some of the highlights of the report, which will be available for purchase at the NCA website.', image: './NewsArticlePictures/Footer.png', id: '15' },
    ],
    headers: [
      { pageTitle: 'Origins', headerPicture: './HeaderPictures/Origins.png', text: 'Langdon Coffee Merchants source green beans from some of the world’s most exciting and XXX coffee origins. Right across the bean belt, we offer roasters a broad selection of traceable (back to the mill, at a minimum) cultivars, processing methods and flavour profiles, meeting the needs of speciality and high-end commercial quality coffee roasters in the UK, New Zealand and Australia. All our beans are extensively cupped for quality assurance at our state-of-the art laboratory in Melbourne by a Q-grader before making their way to our customers. As well as single origin beans, we offer commercial blending for that discerning, bespoke taste.' },
      { pageTitle: 'Contact Us', headerPicture: './HeaderPictures/ContactUs.png' },
      { pageTitle: 'About Us', headerPicture: './HeaderPictures/AboutUs.png' },
      { pageTitle: 'Working with LCM', headerPicture: './HeaderPictures/WorkingWithLcm.png', title: 'We’ve got your green bean needs sorted', text: 'Whatever taste profile, brew method, price or volume requirement you’re after, Langdon Coffee Merchants can help source the perfect green bean for your brew. As well as providing samples, we love to host private cupping sessions to take you through our range first hand – after all, we think it’s best to let our coffee do the talking! With our commercial blending capability, we can also help you create a blend that is unique to your roastery.' },
      { pageTitle: 'News', headerPicture: './HeaderPictures/News.png' }
    ],
    greenBlocks: [
      { greenTitle: '', greenPicture: './GreenBlockWithButton/CuppingAndSampling.png', greenText: `<p class='greenBlockWithButton__text'>As well as customer cuppings, our labs are busy year-round tracking the quality and performance of our beans over time: from the washing station at origin, on arrival at our warehouses (before samples are sent to you), and at three monthly intervals to ensure the beans’ performance holds up.</p><p class='greenBlockWithButton__text'>If you happen to visiting Melbourne, we’d love to show you around our brand new, state-of-the-art cupping laboratory and roasting room.</p><p class='greenBlockWithButton__text'>Alternately, we can arrange to come and cup with you at your roasting business or warehouse, or send green or roasted sample to you via post..</p>` },
      { greenTitle: 'Who we are', greenPicture: './GreenBlockWithButton/WhoWeAre.png', greenText: `<p class='greenBlockWithButton__text'>A small but closely connected global team of dedicated, knowledgeable coffee enthusiasts, Langdon Coffee Merchant’s goal is to build sustainable, meaningful relationships with our producers and customers alike.</p><p class='greenBlockWithButton__text'>We know our coffee beans inside and out, and we only sell what we like to drink. In most cases, we are in direct contact with the producer throughout the growing and harvesting season and cup at origin as often as we can.</p><p class='greenBlockWithButton__text'>When you choose to buy green coffee from Langdon Coffee Merchants, you can trust that your beans have been sourced sustainably, rigorously quality tested and their producers paid fairly</p>` },
      { greenTitle: 'South Melbourne Coffee HQ', greenPicture: './GreenBlockWithButton/HQ.png', greenText: ` <p class='greenBlockWithButton__text'>In 2020, Langdon Coffee Merchants unveiled its state-of-the-art HQ and Cupping Laboratory in leafy South Melbourne – home to some of Melbourne’s favourite roasteries and cafes.</p><p class='greenBlockWithButton__text'>Transforming a neglected mid-19th century warehouse, the South Melbourne HQ features a &lt;&lt;cupping laboratory&gt;&gt;, roasting room, &lt;&lt;other highlights??&gt;&gt;.</p><p class='greenBlockWithButton__text'>Equipped with a W1 Geisen roaster, Langdon Coffee Merchant’s sensory experts can now roast small batch specialty coffees on-site, as well as conducting cupping sessions for customers a drop by for a latte, we’ve got a La Marzocca in the street facing brew-bar.</p>` }
    ]
  }


  render() {
    let { newsInfo, headers, greenBlocks } = this.state;
    return (
      <Router>
        <NavBar />
        {/* <Test newsInfo={newsInfo} /> */}
        <Route exact path="/" render={() => <Home newsInfo={newsInfo} greenBlocks={greenBlocks} />} />
        <Route path="/work-in-progress" component={WorkInProgress} />
        <Route exact path="/news" render={() => <News newsInfo={newsInfo} headers={headers} />} />
        <Route path="/origins" render={() => <Origins headers={headers} />} />
        <Route path="/contact-us" render={() => <ContactUs headers={headers} />} />
        <Route path="/about-lcm" render={() => <AboutLcm headers={headers} greenBlocks={greenBlocks} />} />
        <Route path="/working-with-lcm" render={() => <WorkingWithLcm headers={headers} greenBlocks={greenBlocks} />} />
        <Route
          path="/news/:id"
          render={({ match }) => {
            let { id } = match.params;
            return <SingleArticle newsInfo={newsInfo} articleId={id} headers={headers} />
          }}
        />
        <Footer />
      </Router>
    );
  }
}
